apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: web
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "bin/sh"
      - "-c"
      - "while true; do curl 10.96.117.87:8080; sleep 3; done"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
 
