apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: web
spec:
  containers:
  - name: http-pod
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
