version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql 
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=1234567 
    - SHOW=true
    volumes:
      -"/opt/mysql:/var/lib/mysql"

  # docker-compose -f docker-compose-mysql.yml up -d
  
    



#volumes:
#networks:
