version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql 
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=1234567 
    - SHOW=true
    volumes:
      - "mysql_volume:/var/lib/mysql"
volumes:
  mysql_volume:
  