apiVersion: v1
kind: Service
metadata:
  name: resul-service
  labels:
    name: resul-service
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    - name: resul-app-pod
      app: demo-votting-app 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
