apiVersion: v1
kind: Service
metadata:
  name: votting-service
  labels:
    name: votting-service
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    - name: votting-app-pod
      app: demo-votting-app 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004