apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: my-ns
spec:
  nodeSelector:
    env: dev
  containers:
    - image: nginx:alpine
      name: nginx
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
# muốn add và node worker nào thì edit node worker đó trên labels