apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:

    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      container:
        - name: nginx-controller
          image: nginx
  replicas: 3
  selector:
    matchLabels:  
      type: front-end
# sự khác nhau của replicaset và replication-controller là ở api và selector
# phải match đúng label temple và lable đã khai báo ở trên
