apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>
  Selector: 
      app: myapp
      type: backend
