# One service per container
# Build context should be small
# Avoid unnecessary packages
# Less layers
 
 #FROM nginx:alpine
 #RUN echo "1" >> /usr/share/nginx/html/test.html
 #RUN echo "2" >> /usr/share/nginx/html/test.html
 #RUN echo "3" >> /usr/share/nginx/html/test.html
 FROM nginx:alpine

 ENV webfile /usr/share/nginx/html/test.html

 RUN \
  echo "1" >> $webfile && \
  echo "2" >> $webfile && \
  echo "3" >> $webfile
  